### ISSUE TITLE
"Something went wrong" message

### ISSUE THREAD

**Issue by giacomociani** [sirAndros/KeePassWinHello#64] opened 2021-01-21 08:28 UTC
I had a Remote Desktop Connection open towards a Windows 10 machine on which Keepass with KeePassWinHello was running but not in active use. The remote machine uses WinHello for login. Suddenly, the attached message came up (on the remote machine), with the request to report it on github:

![2021-01-21 09_18_12-GiacP15s - Remote Desktop Connection](https://user-images.githubusercontent.com/3365569/105323694-b4d03f00-5bca-11eb-99df-f3d0eb3e1303.png)

Sorry, I had no time or occasion to investigate this further.

Side note: I don't know if it is a system limitation, but I was forced to attach a screenshot because the pop-up message does not allow to select the error description text to copy/paste.

**Comment by sirAndros** [comment] 2021-03-05 13:36
Hello! Thank you for report!
You can just hit `Ctrl`+`C` on any system pop-up window to copy its text.
As for error - we will investigate it, may be just transform this error into warning as RDP cannot be supported by now.

**Comment by sirAndros** [comment] 2021-03-05 13:47
Closed as duplicate of #51

**Closed by sirAndros** 2021-03-05 13:47 UTC
