### ISSUE TITLE
Startup-Problem.System.NullReferenceException

### ISSUE THREAD

**Issue by mama3235** [sirAndros/KeePassWinHello#99] opened 2023-05-29 09:49 UTC
**Describe the bug**

Error-Message at start of KeePass
**Screenshots**

![Screenshot 2023-05-29 112948](https://github.com/sirAndros/KeePassWinHello/assets/134925870/674e63a6-9b44-49cf-8c1a-3781ff6228d2)

KeePass Options/WindowsHello shows a message that Windows Hello is disabled. However, FingerPrint and PIN are active.

Please complete the following information:

KeePassWinHello 3.2.0.0
Keepass 2.53.1
Windows 11 Pro 22H2

**Hardware info**
TPM AMD Version 3.41.0.5 Spec 2.0

 **Plugin settings**
 
 - [ ] Is persistent mode enabled ("Store keys in Windows Credential Manager" checked): not enabled, not possible so click
 
 **KeePass settings and environment**
 
 - [ ] Is secure desktop enabled - no
 - [ ] Is KeePass running under Administrator (in elevated process) - makes no difference
 - [ ] Was it right after hibernation - no
 - [ ] Was KeePass minified or closed - no
 
 - Installed plugins (if any)
KeePassRPC (1.14.0.0)
KeePassVeraCryptMount (1.0.7.0)
KeePassHello (3.2.0.0)

 - Any specific settings in KeePass/Plugin - none

**Additional context**

**Comment by sirAndros** [comment] 2023-06-02 17:22
Duplicate of #85

**Closed by sirAndros** 2023-06-02 17:22 UTC
